"""Add deleted_by to comments

Revision ID: bb398ba13600
Revises: 2a33e03c1d46
Create Date: 2026-01-09 13:14:24.162771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb398ba13600'
down_revision = '2a33e03c1d46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_by', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('deleted_by')

    # ### end Alembic commands ###
